### ISSUE TITLE
Update dependencies in all repositories

### ISSUE THREAD

**Issue by lukeb2e** [jycouet/VSTSExtensions#33]
**Describe the bug**
I want renovate to update the dependencies in all repositories in my project.
Currently with my attached azure pipeline (see below) it only updates dependencies directly in my project.

eg:
`project/repo1`
`project/repo2`
`project/renovate` <- only updates dependencies here

**To Reproduce**
1. Use the attached `azure-pipeline.yml` and config (see below for both)
2. Run the pipeline

**Expected behavior**
I would expect that the onboarding PR is created either in all repositories or in the manually named repositories in the config.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 76.0.1

**Additional context**

`azure-pipeline.yml`:
```yml
trigger:
- master

schedules:
- cron: "0 6 * * *"
  displayName: Daily
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '12.x'
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
- task: RenovateMe@0
  inputs:
    renovateOptionsVersion: 'latest'
    #renovateOptionsArgs: ''
  env:
    system_accesstoken: $(System.AccessToken)
```

`renovate.json5`:
```json5
{
    // https://docs.renovatebot.com/self-hosted-configuration/
    //"autodiscover": true,
    //"autodiscoverFilter": "project/*",
    "gitAuthor": "RenovateBot <renovate@test.com>",
    "onboarding": true,
    "repositories": [
      "project/renovate",
      "project/repo1"
    ],
    "branchPrefix": "feature/renovate-",
    "packageRules": [
      {
        "packagePatterns": [ "*" ],
        "groupName": "all"
      }
    ],
    "$schema": "https://docs.renovatebot.com/renovate-schema.json"
}
```
