### ISSUE TITLE
Multiple repo approach not working

### ISSUE THREAD

**Issue by timmkrause** [jycouet/VSTSExtensions#43]
**Describe the bug**
I am trying to have a centralized repo/config/Renovate pipeline for multiple repositories approach but the configured repositories are not being targeted.

**To Reproduce**
- All happens within Azure DevOps (Server)
- Have a separate Renovate repository containing only the YAML build pipeline specification `renovate.json(5)` and `config.js`
- Configure `config.js` to specify target repositories like so (taken from [here](https://docs.renovatebot.com/setup-azure-devops/#using-a-single-pipeline-to-update-multiple-repositories)):

```
module.exports = {
    repositories: ['org/repo-a', 'org/repo-b']
};
```

- Run the pipeline
- Find the following in the log, combining the config does not really combine:

```
DEBUG: Parsing configs

DEBUG: Checking for config file in /azp/agent/_work/1/s/config

DEBUG: File config
       "config": {
         "repositories": [
           "org/repo-a",
           "org/repo-b"
         ]
       }

DEBUG: CLI config
       "config": {
         "repositories": ["org/renovate-repo"],
         "platform": "azure",
         "endpoint": "https://my.azure-devops.com/...",
         "token": "***********",
         "hostRules": [
           {"domainName": "github.com", "token": "***********"},
           {
             "domainName": "my.azure-devops.com",
             "username": "irrelephant",
             "password": "***********"
           }
         ]
       }

DEBUG: Env config
       "config": {"hostRules": []}

DEBUG: Combined config
       "config": {
         "repositories": ["org/renovate-repo"],
         "hostRules": [
           {"domainName": "github.com", "token": "***********"},
           {
             "domainName": "my.azure-devops.com",
             "username": "irrelephant",
             "password": "***********"
           }
         ],
         "platform": "azure",
         "endpoint": "https://my.azure-devops.com/...",
         "token": "***********"
       }
```

**Expected behavior**
The combined config should contain repositories read from file config (coming from/configured in `config.js`).

**Additional context**
- Permissions are set, the repos I am targeting are currently having their own, separate, working Renovate pipelines
- Renovate version is set to latest, which currently is 25.47.2
- Also tried

```
    "autodiscover": true,
    "autodiscoverFilter": "org/{repo-a,repo-b}"
```

in `renovate.json` but this does not seem to activate anything, at least there are no logs about the discovery process.

- YAML pipeline definition:

```
trigger: none

pool:
  name: ubuntu-18.04

steps:
- task: UseNode@1
  displayName: 'Use Node 14.17.0'
  inputs:
    version: 14.17.0

- task: jyc.vsts-extensions-renovate-me.default-build-task.RenovateMe@0
  displayName: Renovate
  inputs:
    renovateOptionsArgs: '--host-rules="[{\"domainName\":\"github.com\",\"token\":\"$(GITHUB_COM_TOKEN)\"},{\"domainName\":\"my.azure-devops.com\",\"username\":\"irrelephant\",\"password\":\"$(AZURE_DEVOPS_NUGET_PAT)\"}]"'
```
