### ISSUE TITLE
Add YAML pipeline documentation

### ISSUE THREAD

**Issue by dsimon-onventis** [jycouet/VSTSExtensions#46]
Many are switching from the Classic Azure Pipelines to YAML pipelines. Unfortunately, there is no documentation, how to use this extensions with YAML. What I need to do, is to follow the steps to create a new Classic Pipeline, add the task, fill in the options I need, click on "View YAML", and copy / paste the text. Especially for users which are not familiar with the Classic Pipelines, this is hard to figure out.

**Desired solution**
The documentation should contain the YAML definition of the task with all available options, which I can easily paste into my project. Just like Microsoft does for their tasks. For example, something like this for the Renovate task:

```yaml
- task: jyc.vsts-extensions-renovate-me.default-build-task.RenovateMe@0
  displayName: Renovate
  inputs:
    #renovateOptionsVersion: 'latest' # optional
    #renovateOptionsArgs: '' # optional
```

**Comment by jycouet** [comment]
Thank you for the good idea.
Could you provide the full working example? 

//I'm not using this platform lately... If you don't have something, I will try with a "trial" account.

**Comment by dsimon-onventis** [comment]
This should be a full working example:

```yaml
pool:
  vmImage: ubuntu-latest
steps:
- task: NodeTool@0
  displayName: 'Use Node 14.x'
  inputs:
    versionSpec: 14.x
- task: jyc.vsts-extensions-renovate-me.default-build-task.RenovateMe@0
  displayName: Renovate
  inputs:
    #renovateOptionsVersion: 'latest' # optional
    #renovateOptionsArgs: '' # optional
```
